// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: common/proto/auth/auth.proto

package authProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_RegisterUser_FullMethodName             = "/authProto.AuthService/RegisterUser"
	AuthService_LoginUser_FullMethodName                = "/authProto.AuthService/LoginUser"
	AuthService_LogoutUser_FullMethodName               = "/authProto.AuthService/LogoutUser"
	AuthService_GetUserByIdentifier_FullMethodName      = "/authProto.AuthService/GetUserByIdentifier"
	AuthService_GetUserById_FullMethodName              = "/authProto.AuthService/GetUserById"
	AuthService_UpdateUser_FullMethodName               = "/authProto.AuthService/UpdateUser"
	AuthService_DeleteUser_FullMethodName               = "/authProto.AuthService/DeleteUser"
	AuthService_VerifyAccessToken_FullMethodName        = "/authProto.AuthService/VerifyAccessToken"
	AuthService_RefreshAccessToken_FullMethodName       = "/authProto.AuthService/RefreshAccessToken"
	AuthService_ActivateUser_FullMethodName             = "/authProto.AuthService/ActivateUser"
	AuthService_ResendActivation_FullMethodName         = "/authProto.AuthService/ResendActivation"
	AuthService_RegisterRole_FullMethodName             = "/authProto.AuthService/RegisterRole"
	AuthService_GetRoles_FullMethodName                 = "/authProto.AuthService/GetRoles"
	AuthService_GetRoleByIdentifier_FullMethodName      = "/authProto.AuthService/GetRoleByIdentifier"
	AuthService_GetRoleByID_FullMethodName              = "/authProto.AuthService/GetRoleByID"
	AuthService_UpdateRole_FullMethodName               = "/authProto.AuthService/UpdateRole"
	AuthService_DeleteRole_FullMethodName               = "/authProto.AuthService/DeleteRole"
	AuthService_RegisterCompany_FullMethodName          = "/authProto.AuthService/RegisterCompany"
	AuthService_GetCompanyByIdentifier_FullMethodName   = "/authProto.AuthService/GetCompanyByIdentifier"
	AuthService_GetCompanyByID_FullMethodName           = "/authProto.AuthService/GetCompanyByID"
	AuthService_GetAllCompany_FullMethodName            = "/authProto.AuthService/GetAllCompany"
	AuthService_UpdateCompany_FullMethodName            = "/authProto.AuthService/UpdateCompany"
	AuthService_DeleteCompany_FullMethodName            = "/authProto.AuthService/DeleteCompany"
	AuthService_ForgotPassword_FullMethodName           = "/authProto.AuthService/ForgotPassword"
	AuthService_ResetPassword_FullMethodName            = "/authProto.AuthService/ResetPassword"
	AuthService_GrantCompanyAccess_FullMethodName       = "/authProto.AuthService/GrantCompanyAccess"
	AuthService_RevokeCompanyAccess_FullMethodName      = "/authProto.AuthService/RevokeCompanyAccess"
	AuthService_AssignPermissionsToRole_FullMethodName  = "/authProto.AuthService/AssignPermissionsToRole"
	AuthService_AssignRoleToUser_FullMethodName         = "/authProto.AuthService/AssignRoleToUser"
	AuthService_RemovePermissionFromRole_FullMethodName = "/authProto.AuthService/RemovePermissionFromRole"
	AuthService_RemoveRoleFromUser_FullMethodName       = "/authProto.AuthService/RemoveRoleFromUser"
	AuthService_GetRolePermissions_FullMethodName       = "/authProto.AuthService/GetRolePermissions"
	AuthService_GetUserPermissions_FullMethodName       = "/authProto.AuthService/GetUserPermissions"
	AuthService_CheckUserPermission_FullMethodName      = "/authProto.AuthService/CheckUserPermission"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	// User
	RegisterUser(ctx context.Context, in *UserRegisterPayload, opts ...grpc.CallOption) (*User, error)
	LoginUser(ctx context.Context, in *LoginUserPayload, opts ...grpc.CallOption) (*LoginUserResponse, error)
	LogoutUser(ctx context.Context, in *LogoutUserPayload, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetUserByIdentifier(ctx context.Context, in *GetUserByIdentifierPayload, opts ...grpc.CallOption) (*User, error)
	GetUserById(ctx context.Context, in *GetUserByIdPayload, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *UpdateUserPayload, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *DeleteUserPayload, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	VerifyAccessToken(ctx context.Context, in *VerifyAccessTokenPayload, opts ...grpc.CallOption) (*User, error)
	RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenPayload, opts ...grpc.CallOption) (*LoginUserResponse, error)
	ActivateUser(ctx context.Context, in *ActivateUserPayload, opts ...grpc.CallOption) (*User, error)
	ResendActivation(ctx context.Context, in *ResendActivationPayload, opts ...grpc.CallOption) (*User, error)
	// Role management
	RegisterRole(ctx context.Context, in *RoleRegisterPayload, opts ...grpc.CallOption) (*Role, error)
	GetRoles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RoleList, error)
	GetRoleByIdentifier(ctx context.Context, in *GetRoleByIdentifierPayload, opts ...grpc.CallOption) (*Role, error)
	GetRoleByID(ctx context.Context, in *GetRoleByIdPayload, opts ...grpc.CallOption) (*Role, error)
	UpdateRole(ctx context.Context, in *UpdateRolePayload, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteRole(ctx context.Context, in *DeleteRolePayload, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Company management
	RegisterCompany(ctx context.Context, in *CompanyRegisterPayload, opts ...grpc.CallOption) (*Company, error)
	GetCompanyByIdentifier(ctx context.Context, in *GetCompanyByIdentifierPayload, opts ...grpc.CallOption) (*Company, error)
	GetCompanyByID(ctx context.Context, in *GetCompanyByIDPayload, opts ...grpc.CallOption) (*Company, error)
	GetAllCompany(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CompanyList, error)
	UpdateCompany(ctx context.Context, in *CompanyRegisterPayload, opts ...grpc.CallOption) (*Company, error)
	DeleteCompany(ctx context.Context, in *DeleteCompanyPayload, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Account Management
	ForgotPassword(ctx context.Context, in *ForgotPasswordPayload, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResetPassword(ctx context.Context, in *ResetPasswordPayload, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Admin
	GrantCompanyAccess(ctx context.Context, in *GrantCompanyAccessPayload, opts ...grpc.CallOption) (*User, error)
	RevokeCompanyAccess(ctx context.Context, in *RevokeCompanyAccessPayload, opts ...grpc.CallOption) (*User, error)
	// Permission Management
	AssignPermissionsToRole(ctx context.Context, in *AssignPermissionsToRolePayload, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AssignRoleToUser(ctx context.Context, in *AssignRoleToUserPayload, opts ...grpc.CallOption) (*User, error)
	RemovePermissionFromRole(ctx context.Context, in *RemovePermissionFromRolePayload, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveRoleFromUser(ctx context.Context, in *RemoveRoleFromUserPayload, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetRolePermissions(ctx context.Context, in *GetRolePermissionsPayload, opts ...grpc.CallOption) (*GetRolePermissionsResponse, error)
	GetUserPermissions(ctx context.Context, in *GetUserPermissionsPayload, opts ...grpc.CallOption) (*GetUserPermissionsResponse, error)
	CheckUserPermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*CheckPermissionResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) RegisterUser(ctx context.Context, in *UserRegisterPayload, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LoginUser(ctx context.Context, in *LoginUserPayload, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, AuthService_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LogoutUser(ctx context.Context, in *LogoutUserPayload, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthService_LogoutUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUserByIdentifier(ctx context.Context, in *GetUserByIdentifierPayload, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_GetUserByIdentifier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUserById(ctx context.Context, in *GetUserByIdPayload, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_GetUserById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateUser(ctx context.Context, in *UpdateUserPayload, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DeleteUser(ctx context.Context, in *DeleteUserPayload, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, AuthService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyAccessToken(ctx context.Context, in *VerifyAccessTokenPayload, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_VerifyAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenPayload, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, AuthService_RefreshAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ActivateUser(ctx context.Context, in *ActivateUserPayload, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_ActivateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ResendActivation(ctx context.Context, in *ResendActivationPayload, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_ResendActivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RegisterRole(ctx context.Context, in *RoleRegisterPayload, opts ...grpc.CallOption) (*Role, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Role)
	err := c.cc.Invoke(ctx, AuthService_RegisterRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetRoles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RoleList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleList)
	err := c.cc.Invoke(ctx, AuthService_GetRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetRoleByIdentifier(ctx context.Context, in *GetRoleByIdentifierPayload, opts ...grpc.CallOption) (*Role, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Role)
	err := c.cc.Invoke(ctx, AuthService_GetRoleByIdentifier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetRoleByID(ctx context.Context, in *GetRoleByIdPayload, opts ...grpc.CallOption) (*Role, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Role)
	err := c.cc.Invoke(ctx, AuthService_GetRoleByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateRole(ctx context.Context, in *UpdateRolePayload, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthService_UpdateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DeleteRole(ctx context.Context, in *DeleteRolePayload, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthService_DeleteRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RegisterCompany(ctx context.Context, in *CompanyRegisterPayload, opts ...grpc.CallOption) (*Company, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Company)
	err := c.cc.Invoke(ctx, AuthService_RegisterCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetCompanyByIdentifier(ctx context.Context, in *GetCompanyByIdentifierPayload, opts ...grpc.CallOption) (*Company, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Company)
	err := c.cc.Invoke(ctx, AuthService_GetCompanyByIdentifier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetCompanyByID(ctx context.Context, in *GetCompanyByIDPayload, opts ...grpc.CallOption) (*Company, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Company)
	err := c.cc.Invoke(ctx, AuthService_GetCompanyByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetAllCompany(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CompanyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompanyList)
	err := c.cc.Invoke(ctx, AuthService_GetAllCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateCompany(ctx context.Context, in *CompanyRegisterPayload, opts ...grpc.CallOption) (*Company, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Company)
	err := c.cc.Invoke(ctx, AuthService_UpdateCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DeleteCompany(ctx context.Context, in *DeleteCompanyPayload, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthService_DeleteCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ForgotPassword(ctx context.Context, in *ForgotPasswordPayload, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthService_ForgotPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordPayload, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthService_ResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GrantCompanyAccess(ctx context.Context, in *GrantCompanyAccessPayload, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_GrantCompanyAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RevokeCompanyAccess(ctx context.Context, in *RevokeCompanyAccessPayload, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_RevokeCompanyAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AssignPermissionsToRole(ctx context.Context, in *AssignPermissionsToRolePayload, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthService_AssignPermissionsToRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AssignRoleToUser(ctx context.Context, in *AssignRoleToUserPayload, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_AssignRoleToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RemovePermissionFromRole(ctx context.Context, in *RemovePermissionFromRolePayload, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthService_RemovePermissionFromRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RemoveRoleFromUser(ctx context.Context, in *RemoveRoleFromUserPayload, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthService_RemoveRoleFromUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetRolePermissions(ctx context.Context, in *GetRolePermissionsPayload, opts ...grpc.CallOption) (*GetRolePermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRolePermissionsResponse)
	err := c.cc.Invoke(ctx, AuthService_GetRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUserPermissions(ctx context.Context, in *GetUserPermissionsPayload, opts ...grpc.CallOption) (*GetUserPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPermissionsResponse)
	err := c.cc.Invoke(ctx, AuthService_GetUserPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CheckUserPermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*CheckPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPermissionResponse)
	err := c.cc.Invoke(ctx, AuthService_CheckUserPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	// User
	RegisterUser(context.Context, *UserRegisterPayload) (*User, error)
	LoginUser(context.Context, *LoginUserPayload) (*LoginUserResponse, error)
	LogoutUser(context.Context, *LogoutUserPayload) (*emptypb.Empty, error)
	GetUserByIdentifier(context.Context, *GetUserByIdentifierPayload) (*User, error)
	GetUserById(context.Context, *GetUserByIdPayload) (*User, error)
	UpdateUser(context.Context, *UpdateUserPayload) (*User, error)
	DeleteUser(context.Context, *DeleteUserPayload) (*DeleteUserResponse, error)
	VerifyAccessToken(context.Context, *VerifyAccessTokenPayload) (*User, error)
	RefreshAccessToken(context.Context, *RefreshAccessTokenPayload) (*LoginUserResponse, error)
	ActivateUser(context.Context, *ActivateUserPayload) (*User, error)
	ResendActivation(context.Context, *ResendActivationPayload) (*User, error)
	// Role management
	RegisterRole(context.Context, *RoleRegisterPayload) (*Role, error)
	GetRoles(context.Context, *emptypb.Empty) (*RoleList, error)
	GetRoleByIdentifier(context.Context, *GetRoleByIdentifierPayload) (*Role, error)
	GetRoleByID(context.Context, *GetRoleByIdPayload) (*Role, error)
	UpdateRole(context.Context, *UpdateRolePayload) (*emptypb.Empty, error)
	DeleteRole(context.Context, *DeleteRolePayload) (*emptypb.Empty, error)
	// Company management
	RegisterCompany(context.Context, *CompanyRegisterPayload) (*Company, error)
	GetCompanyByIdentifier(context.Context, *GetCompanyByIdentifierPayload) (*Company, error)
	GetCompanyByID(context.Context, *GetCompanyByIDPayload) (*Company, error)
	GetAllCompany(context.Context, *emptypb.Empty) (*CompanyList, error)
	UpdateCompany(context.Context, *CompanyRegisterPayload) (*Company, error)
	DeleteCompany(context.Context, *DeleteCompanyPayload) (*emptypb.Empty, error)
	// Account Management
	ForgotPassword(context.Context, *ForgotPasswordPayload) (*emptypb.Empty, error)
	ResetPassword(context.Context, *ResetPasswordPayload) (*emptypb.Empty, error)
	// Admin
	GrantCompanyAccess(context.Context, *GrantCompanyAccessPayload) (*User, error)
	RevokeCompanyAccess(context.Context, *RevokeCompanyAccessPayload) (*User, error)
	// Permission Management
	AssignPermissionsToRole(context.Context, *AssignPermissionsToRolePayload) (*emptypb.Empty, error)
	AssignRoleToUser(context.Context, *AssignRoleToUserPayload) (*User, error)
	RemovePermissionFromRole(context.Context, *RemovePermissionFromRolePayload) (*emptypb.Empty, error)
	RemoveRoleFromUser(context.Context, *RemoveRoleFromUserPayload) (*emptypb.Empty, error)
	GetRolePermissions(context.Context, *GetRolePermissionsPayload) (*GetRolePermissionsResponse, error)
	GetUserPermissions(context.Context, *GetUserPermissionsPayload) (*GetUserPermissionsResponse, error)
	CheckUserPermission(context.Context, *CheckPermissionRequest) (*CheckPermissionResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) RegisterUser(context.Context, *UserRegisterPayload) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedAuthServiceServer) LoginUser(context.Context, *LoginUserPayload) (*LoginUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedAuthServiceServer) LogoutUser(context.Context, *LogoutUserPayload) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LogoutUser not implemented")
}
func (UnimplementedAuthServiceServer) GetUserByIdentifier(context.Context, *GetUserByIdentifierPayload) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByIdentifier not implemented")
}
func (UnimplementedAuthServiceServer) GetUserById(context.Context, *GetUserByIdPayload) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserById not implemented")
}
func (UnimplementedAuthServiceServer) UpdateUser(context.Context, *UpdateUserPayload) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedAuthServiceServer) DeleteUser(context.Context, *DeleteUserPayload) (*DeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedAuthServiceServer) VerifyAccessToken(context.Context, *VerifyAccessTokenPayload) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAccessToken not implemented")
}
func (UnimplementedAuthServiceServer) RefreshAccessToken(context.Context, *RefreshAccessTokenPayload) (*LoginUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshAccessToken not implemented")
}
func (UnimplementedAuthServiceServer) ActivateUser(context.Context, *ActivateUserPayload) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateUser not implemented")
}
func (UnimplementedAuthServiceServer) ResendActivation(context.Context, *ResendActivationPayload) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method ResendActivation not implemented")
}
func (UnimplementedAuthServiceServer) RegisterRole(context.Context, *RoleRegisterPayload) (*Role, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterRole not implemented")
}
func (UnimplementedAuthServiceServer) GetRoles(context.Context, *emptypb.Empty) (*RoleList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoles not implemented")
}
func (UnimplementedAuthServiceServer) GetRoleByIdentifier(context.Context, *GetRoleByIdentifierPayload) (*Role, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoleByIdentifier not implemented")
}
func (UnimplementedAuthServiceServer) GetRoleByID(context.Context, *GetRoleByIdPayload) (*Role, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoleByID not implemented")
}
func (UnimplementedAuthServiceServer) UpdateRole(context.Context, *UpdateRolePayload) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRole not implemented")
}
func (UnimplementedAuthServiceServer) DeleteRole(context.Context, *DeleteRolePayload) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRole not implemented")
}
func (UnimplementedAuthServiceServer) RegisterCompany(context.Context, *CompanyRegisterPayload) (*Company, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCompany not implemented")
}
func (UnimplementedAuthServiceServer) GetCompanyByIdentifier(context.Context, *GetCompanyByIdentifierPayload) (*Company, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompanyByIdentifier not implemented")
}
func (UnimplementedAuthServiceServer) GetCompanyByID(context.Context, *GetCompanyByIDPayload) (*Company, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompanyByID not implemented")
}
func (UnimplementedAuthServiceServer) GetAllCompany(context.Context, *emptypb.Empty) (*CompanyList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllCompany not implemented")
}
func (UnimplementedAuthServiceServer) UpdateCompany(context.Context, *CompanyRegisterPayload) (*Company, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCompany not implemented")
}
func (UnimplementedAuthServiceServer) DeleteCompany(context.Context, *DeleteCompanyPayload) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCompany not implemented")
}
func (UnimplementedAuthServiceServer) ForgotPassword(context.Context, *ForgotPasswordPayload) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ForgotPassword not implemented")
}
func (UnimplementedAuthServiceServer) ResetPassword(context.Context, *ResetPasswordPayload) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedAuthServiceServer) GrantCompanyAccess(context.Context, *GrantCompanyAccessPayload) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantCompanyAccess not implemented")
}
func (UnimplementedAuthServiceServer) RevokeCompanyAccess(context.Context, *RevokeCompanyAccessPayload) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCompanyAccess not implemented")
}
func (UnimplementedAuthServiceServer) AssignPermissionsToRole(context.Context, *AssignPermissionsToRolePayload) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignPermissionsToRole not implemented")
}
func (UnimplementedAuthServiceServer) AssignRoleToUser(context.Context, *AssignRoleToUserPayload) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignRoleToUser not implemented")
}
func (UnimplementedAuthServiceServer) RemovePermissionFromRole(context.Context, *RemovePermissionFromRolePayload) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePermissionFromRole not implemented")
}
func (UnimplementedAuthServiceServer) RemoveRoleFromUser(context.Context, *RemoveRoleFromUserPayload) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRoleFromUser not implemented")
}
func (UnimplementedAuthServiceServer) GetRolePermissions(context.Context, *GetRolePermissionsPayload) (*GetRolePermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRolePermissions not implemented")
}
func (UnimplementedAuthServiceServer) GetUserPermissions(context.Context, *GetUserPermissionsPayload) (*GetUserPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPermissions not implemented")
}
func (UnimplementedAuthServiceServer) CheckUserPermission(context.Context, *CheckPermissionRequest) (*CheckPermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUserPermission not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisterPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RegisterUser(ctx, req.(*UserRegisterPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LoginUser(ctx, req.(*LoginUserPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LogoutUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutUserPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LogoutUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_LogoutUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LogoutUser(ctx, req.(*LogoutUserPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUserByIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIdentifierPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUserByIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUserByIdentifier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUserByIdentifier(ctx, req.(*GetUserByIdentifierPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIdPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUserById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUserById(ctx, req.(*GetUserByIdPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateUser(ctx, req.(*UpdateUserPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteUser(ctx, req.(*DeleteUserPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAccessTokenPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyAccessToken(ctx, req.(*VerifyAccessTokenPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshAccessTokenPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RefreshAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshAccessToken(ctx, req.(*RefreshAccessTokenPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ActivateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateUserPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ActivateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ActivateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ActivateUser(ctx, req.(*ActivateUserPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ResendActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendActivationPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ResendActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ResendActivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ResendActivation(ctx, req.(*ResendActivationPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RegisterRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleRegisterPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RegisterRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RegisterRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RegisterRole(ctx, req.(*RoleRegisterPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetRoles(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetRoleByIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleByIdentifierPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetRoleByIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetRoleByIdentifier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetRoleByIdentifier(ctx, req.(*GetRoleByIdentifierPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetRoleByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleByIdPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetRoleByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetRoleByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetRoleByID(ctx, req.(*GetRoleByIdPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRolePayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UpdateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateRole(ctx, req.(*UpdateRolePayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRolePayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_DeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteRole(ctx, req.(*DeleteRolePayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RegisterCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanyRegisterPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RegisterCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RegisterCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RegisterCompany(ctx, req.(*CompanyRegisterPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetCompanyByIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyByIdentifierPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetCompanyByIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetCompanyByIdentifier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetCompanyByIdentifier(ctx, req.(*GetCompanyByIdentifierPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetCompanyByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyByIDPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetCompanyByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetCompanyByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetCompanyByID(ctx, req.(*GetCompanyByIDPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetAllCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetAllCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetAllCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetAllCompany(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanyRegisterPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UpdateCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateCompany(ctx, req.(*CompanyRegisterPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DeleteCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCompanyPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_DeleteCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteCompany(ctx, req.(*DeleteCompanyPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ForgotPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ForgotPassword(ctx, req.(*ForgotPasswordPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ResetPassword(ctx, req.(*ResetPasswordPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GrantCompanyAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantCompanyAccessPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GrantCompanyAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GrantCompanyAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GrantCompanyAccess(ctx, req.(*GrantCompanyAccessPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RevokeCompanyAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCompanyAccessPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RevokeCompanyAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RevokeCompanyAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RevokeCompanyAccess(ctx, req.(*RevokeCompanyAccessPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AssignPermissionsToRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignPermissionsToRolePayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AssignPermissionsToRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_AssignPermissionsToRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AssignPermissionsToRole(ctx, req.(*AssignPermissionsToRolePayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AssignRoleToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRoleToUserPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AssignRoleToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_AssignRoleToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AssignRoleToUser(ctx, req.(*AssignRoleToUserPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RemovePermissionFromRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePermissionFromRolePayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RemovePermissionFromRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RemovePermissionFromRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RemovePermissionFromRole(ctx, req.(*RemovePermissionFromRolePayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RemoveRoleFromUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRoleFromUserPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RemoveRoleFromUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RemoveRoleFromUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RemoveRoleFromUser(ctx, req.(*RemoveRoleFromUserPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolePermissionsPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetRolePermissions(ctx, req.(*GetRolePermissionsPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUserPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPermissionsPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUserPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUserPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUserPermissions(ctx, req.(*GetUserPermissionsPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckUserPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckUserPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CheckUserPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckUserPermission(ctx, req.(*CheckPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authProto.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _AuthService_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _AuthService_LoginUser_Handler,
		},
		{
			MethodName: "LogoutUser",
			Handler:    _AuthService_LogoutUser_Handler,
		},
		{
			MethodName: "GetUserByIdentifier",
			Handler:    _AuthService_GetUserByIdentifier_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _AuthService_GetUserById_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _AuthService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _AuthService_DeleteUser_Handler,
		},
		{
			MethodName: "VerifyAccessToken",
			Handler:    _AuthService_VerifyAccessToken_Handler,
		},
		{
			MethodName: "RefreshAccessToken",
			Handler:    _AuthService_RefreshAccessToken_Handler,
		},
		{
			MethodName: "ActivateUser",
			Handler:    _AuthService_ActivateUser_Handler,
		},
		{
			MethodName: "ResendActivation",
			Handler:    _AuthService_ResendActivation_Handler,
		},
		{
			MethodName: "RegisterRole",
			Handler:    _AuthService_RegisterRole_Handler,
		},
		{
			MethodName: "GetRoles",
			Handler:    _AuthService_GetRoles_Handler,
		},
		{
			MethodName: "GetRoleByIdentifier",
			Handler:    _AuthService_GetRoleByIdentifier_Handler,
		},
		{
			MethodName: "GetRoleByID",
			Handler:    _AuthService_GetRoleByID_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _AuthService_UpdateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _AuthService_DeleteRole_Handler,
		},
		{
			MethodName: "RegisterCompany",
			Handler:    _AuthService_RegisterCompany_Handler,
		},
		{
			MethodName: "GetCompanyByIdentifier",
			Handler:    _AuthService_GetCompanyByIdentifier_Handler,
		},
		{
			MethodName: "GetCompanyByID",
			Handler:    _AuthService_GetCompanyByID_Handler,
		},
		{
			MethodName: "GetAllCompany",
			Handler:    _AuthService_GetAllCompany_Handler,
		},
		{
			MethodName: "UpdateCompany",
			Handler:    _AuthService_UpdateCompany_Handler,
		},
		{
			MethodName: "DeleteCompany",
			Handler:    _AuthService_DeleteCompany_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _AuthService_ForgotPassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _AuthService_ResetPassword_Handler,
		},
		{
			MethodName: "GrantCompanyAccess",
			Handler:    _AuthService_GrantCompanyAccess_Handler,
		},
		{
			MethodName: "RevokeCompanyAccess",
			Handler:    _AuthService_RevokeCompanyAccess_Handler,
		},
		{
			MethodName: "AssignPermissionsToRole",
			Handler:    _AuthService_AssignPermissionsToRole_Handler,
		},
		{
			MethodName: "AssignRoleToUser",
			Handler:    _AuthService_AssignRoleToUser_Handler,
		},
		{
			MethodName: "RemovePermissionFromRole",
			Handler:    _AuthService_RemovePermissionFromRole_Handler,
		},
		{
			MethodName: "RemoveRoleFromUser",
			Handler:    _AuthService_RemoveRoleFromUser_Handler,
		},
		{
			MethodName: "GetRolePermissions",
			Handler:    _AuthService_GetRolePermissions_Handler,
		},
		{
			MethodName: "GetUserPermissions",
			Handler:    _AuthService_GetUserPermissions_Handler,
		},
		{
			MethodName: "CheckUserPermission",
			Handler:    _AuthService_CheckUserPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/proto/auth/auth.proto",
}
