// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: common/proto/inventory/inventory.proto

package inventoryProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_CreateInventory_FullMethodName                        = "/inventoryProto.InventoryService/CreateInventory"
	InventoryService_GetInventoryByProductIDAndCompanyID_FullMethodName    = "/inventoryProto.InventoryService/GetInventoryByProductIDAndCompanyID"
	InventoryService_DeleteInventoryByProductIDAndCompanyID_FullMethodName = "/inventoryProto.InventoryService/DeleteInventoryByProductIDAndCompanyID"
	InventoryService_UpdateInventory_FullMethodName                        = "/inventoryProto.InventoryService/UpdateInventory"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Inventory Service
type InventoryServiceClient interface {
	CreateInventory(ctx context.Context, in *CreateInventoryPayload, opts ...grpc.CallOption) (*Inventory, error)
	GetInventoryByProductIDAndCompanyID(ctx context.Context, in *GetInventoryByProductIDAndCompanyIDPayload, opts ...grpc.CallOption) (*Inventory, error)
	DeleteInventoryByProductIDAndCompanyID(ctx context.Context, in *DeleteInventoryByProductIDAndCompanyIDPayload, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateInventory(ctx context.Context, in *UpdateInventoryPayload, opts ...grpc.CallOption) (*Inventory, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) CreateInventory(ctx context.Context, in *CreateInventoryPayload, opts ...grpc.CallOption) (*Inventory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Inventory)
	err := c.cc.Invoke(ctx, InventoryService_CreateInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetInventoryByProductIDAndCompanyID(ctx context.Context, in *GetInventoryByProductIDAndCompanyIDPayload, opts ...grpc.CallOption) (*Inventory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Inventory)
	err := c.cc.Invoke(ctx, InventoryService_GetInventoryByProductIDAndCompanyID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) DeleteInventoryByProductIDAndCompanyID(ctx context.Context, in *DeleteInventoryByProductIDAndCompanyIDPayload, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, InventoryService_DeleteInventoryByProductIDAndCompanyID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) UpdateInventory(ctx context.Context, in *UpdateInventoryPayload, opts ...grpc.CallOption) (*Inventory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Inventory)
	err := c.cc.Invoke(ctx, InventoryService_UpdateInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
//
// Inventory Service
type InventoryServiceServer interface {
	CreateInventory(context.Context, *CreateInventoryPayload) (*Inventory, error)
	GetInventoryByProductIDAndCompanyID(context.Context, *GetInventoryByProductIDAndCompanyIDPayload) (*Inventory, error)
	DeleteInventoryByProductIDAndCompanyID(context.Context, *DeleteInventoryByProductIDAndCompanyIDPayload) (*emptypb.Empty, error)
	UpdateInventory(context.Context, *UpdateInventoryPayload) (*Inventory, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) CreateInventory(context.Context, *CreateInventoryPayload) (*Inventory, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInventory not implemented")
}
func (UnimplementedInventoryServiceServer) GetInventoryByProductIDAndCompanyID(context.Context, *GetInventoryByProductIDAndCompanyIDPayload) (*Inventory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventoryByProductIDAndCompanyID not implemented")
}
func (UnimplementedInventoryServiceServer) DeleteInventoryByProductIDAndCompanyID(context.Context, *DeleteInventoryByProductIDAndCompanyIDPayload) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteInventoryByProductIDAndCompanyID not implemented")
}
func (UnimplementedInventoryServiceServer) UpdateInventory(context.Context, *UpdateInventoryPayload) (*Inventory, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInventory not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_CreateInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInventoryPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateInventory(ctx, req.(*CreateInventoryPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetInventoryByProductIDAndCompanyID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryByProductIDAndCompanyIDPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetInventoryByProductIDAndCompanyID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetInventoryByProductIDAndCompanyID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetInventoryByProductIDAndCompanyID(ctx, req.(*GetInventoryByProductIDAndCompanyIDPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_DeleteInventoryByProductIDAndCompanyID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInventoryByProductIDAndCompanyIDPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).DeleteInventoryByProductIDAndCompanyID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_DeleteInventoryByProductIDAndCompanyID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).DeleteInventoryByProductIDAndCompanyID(ctx, req.(*DeleteInventoryByProductIDAndCompanyIDPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_UpdateInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInventoryPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).UpdateInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_UpdateInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).UpdateInventory(ctx, req.(*UpdateInventoryPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventoryProto.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInventory",
			Handler:    _InventoryService_CreateInventory_Handler,
		},
		{
			MethodName: "GetInventoryByProductIDAndCompanyID",
			Handler:    _InventoryService_GetInventoryByProductIDAndCompanyID_Handler,
		},
		{
			MethodName: "DeleteInventoryByProductIDAndCompanyID",
			Handler:    _InventoryService_DeleteInventoryByProductIDAndCompanyID_Handler,
		},
		{
			MethodName: "UpdateInventory",
			Handler:    _InventoryService_UpdateInventory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/proto/inventory/inventory.proto",
}
