// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: common/proto/inventory/inventory.proto

package inventoryProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Main Models
type Inventory struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId         string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CompanyId         string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	AvailableQuantity int64                  `protobuf:"varint,4,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	ThresholdQuantity int64                  `protobuf:"varint,5,opt,name=threshold_quantity,json=thresholdQuantity,proto3" json:"threshold_quantity,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_common_proto_inventory_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_inventory_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_common_proto_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Inventory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Inventory) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Inventory) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *Inventory) GetAvailableQuantity() int64 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *Inventory) GetThresholdQuantity() int64 {
	if x != nil {
		return x.ThresholdQuantity
	}
	return 0
}

func (x *Inventory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Inventory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Inventory Create Models
type CreateInventoryPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CompanyId         string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	AvailableQuantity int64                  `protobuf:"varint,3,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	ThresholdQuantity int64                  `protobuf:"varint,4,opt,name=threshold_quantity,json=thresholdQuantity,proto3" json:"threshold_quantity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateInventoryPayload) Reset() {
	*x = CreateInventoryPayload{}
	mi := &file_common_proto_inventory_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryPayload) ProtoMessage() {}

func (x *CreateInventoryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_inventory_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryPayload.ProtoReflect.Descriptor instead.
func (*CreateInventoryPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInventoryPayload) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateInventoryPayload) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *CreateInventoryPayload) GetAvailableQuantity() int64 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *CreateInventoryPayload) GetThresholdQuantity() int64 {
	if x != nil {
		return x.ThresholdQuantity
	}
	return 0
}

// Get Inventory By ProductID & CompanyID Models
type GetInventoryByProductIDAndCompanyIDPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryByProductIDAndCompanyIDPayload) Reset() {
	*x = GetInventoryByProductIDAndCompanyIDPayload{}
	mi := &file_common_proto_inventory_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryByProductIDAndCompanyIDPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryByProductIDAndCompanyIDPayload) ProtoMessage() {}

func (x *GetInventoryByProductIDAndCompanyIDPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_inventory_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryByProductIDAndCompanyIDPayload.ProtoReflect.Descriptor instead.
func (*GetInventoryByProductIDAndCompanyIDPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_inventory_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetInventoryByProductIDAndCompanyIDPayload) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetInventoryByProductIDAndCompanyIDPayload) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

// Delete Inventory By ProductID & CompanyID Models
type DeleteInventoryByProductIDAndCompanyIDPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInventoryByProductIDAndCompanyIDPayload) Reset() {
	*x = DeleteInventoryByProductIDAndCompanyIDPayload{}
	mi := &file_common_proto_inventory_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInventoryByProductIDAndCompanyIDPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInventoryByProductIDAndCompanyIDPayload) ProtoMessage() {}

func (x *DeleteInventoryByProductIDAndCompanyIDPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_inventory_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInventoryByProductIDAndCompanyIDPayload.ProtoReflect.Descriptor instead.
func (*DeleteInventoryByProductIDAndCompanyIDPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_inventory_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteInventoryByProductIDAndCompanyIDPayload) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *DeleteInventoryByProductIDAndCompanyIDPayload) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

// Update Inventory Models
type UpdateInventoryPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CompanyId         string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	AvailableQuantity int64                  `protobuf:"varint,3,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	ThresholdQuantity int64                  `protobuf:"varint,4,opt,name=threshold_quantity,json=thresholdQuantity,proto3" json:"threshold_quantity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateInventoryPayload) Reset() {
	*x = UpdateInventoryPayload{}
	mi := &file_common_proto_inventory_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryPayload) ProtoMessage() {}

func (x *UpdateInventoryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_inventory_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryPayload.ProtoReflect.Descriptor instead.
func (*UpdateInventoryPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_inventory_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateInventoryPayload) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateInventoryPayload) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *UpdateInventoryPayload) GetAvailableQuantity() int64 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *UpdateInventoryPayload) GetThresholdQuantity() int64 {
	if x != nil {
		return x.ThresholdQuantity
	}
	return 0
}

var File_common_proto_inventory_inventory_proto protoreflect.FileDescriptor

const file_common_proto_inventory_inventory_proto_rawDesc = "" +
	"\n" +
	"&common/proto/inventory/inventory.proto\x12\x0einventoryProto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xad\x02\n" +
	"\tInventory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\x12-\n" +
	"\x12available_quantity\x18\x04 \x01(\x03R\x11availableQuantity\x12-\n" +
	"\x12threshold_quantity\x18\x05 \x01(\x03R\x11thresholdQuantity\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb4\x01\n" +
	"\x16CreateInventoryPayload\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12-\n" +
	"\x12available_quantity\x18\x03 \x01(\x03R\x11availableQuantity\x12-\n" +
	"\x12threshold_quantity\x18\x04 \x01(\x03R\x11thresholdQuantity\"j\n" +
	"*GetInventoryByProductIDAndCompanyIDPayload\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\"m\n" +
	"-DeleteInventoryByProductIDAndCompanyIDPayload\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\"\xb4\x01\n" +
	"\x16UpdateInventoryPayload\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12-\n" +
	"\x12available_quantity\x18\x03 \x01(\x03R\x11availableQuantity\x12-\n" +
	"\x12threshold_quantity\x18\x04 \x01(\x03R\x11thresholdQuantity2\xbd\x03\n" +
	"\x10InventoryService\x12T\n" +
	"\x0fCreateInventory\x12&.inventoryProto.CreateInventoryPayload\x1a\x19.inventoryProto.Inventory\x12|\n" +
	"#GetInventoryByProductIDAndCompanyID\x12:.inventoryProto.GetInventoryByProductIDAndCompanyIDPayload\x1a\x19.inventoryProto.Inventory\x12\x7f\n" +
	"&DeleteInventoryByProductIDAndCompanyID\x12=.inventoryProto.DeleteInventoryByProductIDAndCompanyIDPayload\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x0fUpdateInventory\x12&.inventoryProto.UpdateInventoryPayload\x1a\x19.inventoryProto.InventoryB Z\x1einventory/proto;inventoryProtob\x06proto3"

var (
	file_common_proto_inventory_inventory_proto_rawDescOnce sync.Once
	file_common_proto_inventory_inventory_proto_rawDescData []byte
)

func file_common_proto_inventory_inventory_proto_rawDescGZIP() []byte {
	file_common_proto_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_common_proto_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_inventory_inventory_proto_rawDesc), len(file_common_proto_inventory_inventory_proto_rawDesc)))
	})
	return file_common_proto_inventory_inventory_proto_rawDescData
}

var file_common_proto_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_proto_inventory_inventory_proto_goTypes = []any{
	(*Inventory)(nil),                                     // 0: inventoryProto.Inventory
	(*CreateInventoryPayload)(nil),                        // 1: inventoryProto.CreateInventoryPayload
	(*GetInventoryByProductIDAndCompanyIDPayload)(nil),    // 2: inventoryProto.GetInventoryByProductIDAndCompanyIDPayload
	(*DeleteInventoryByProductIDAndCompanyIDPayload)(nil), // 3: inventoryProto.DeleteInventoryByProductIDAndCompanyIDPayload
	(*UpdateInventoryPayload)(nil),                        // 4: inventoryProto.UpdateInventoryPayload
	(*timestamppb.Timestamp)(nil),                         // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                                 // 6: google.protobuf.Empty
}
var file_common_proto_inventory_inventory_proto_depIdxs = []int32{
	5, // 0: inventoryProto.Inventory.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: inventoryProto.Inventory.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: inventoryProto.InventoryService.CreateInventory:input_type -> inventoryProto.CreateInventoryPayload
	2, // 3: inventoryProto.InventoryService.GetInventoryByProductIDAndCompanyID:input_type -> inventoryProto.GetInventoryByProductIDAndCompanyIDPayload
	3, // 4: inventoryProto.InventoryService.DeleteInventoryByProductIDAndCompanyID:input_type -> inventoryProto.DeleteInventoryByProductIDAndCompanyIDPayload
	4, // 5: inventoryProto.InventoryService.UpdateInventory:input_type -> inventoryProto.UpdateInventoryPayload
	0, // 6: inventoryProto.InventoryService.CreateInventory:output_type -> inventoryProto.Inventory
	0, // 7: inventoryProto.InventoryService.GetInventoryByProductIDAndCompanyID:output_type -> inventoryProto.Inventory
	6, // 8: inventoryProto.InventoryService.DeleteInventoryByProductIDAndCompanyID:output_type -> google.protobuf.Empty
	0, // 9: inventoryProto.InventoryService.UpdateInventory:output_type -> inventoryProto.Inventory
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_inventory_inventory_proto_init() }
func file_common_proto_inventory_inventory_proto_init() {
	if File_common_proto_inventory_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_inventory_inventory_proto_rawDesc), len(file_common_proto_inventory_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_common_proto_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_common_proto_inventory_inventory_proto_msgTypes,
	}.Build()
	File_common_proto_inventory_inventory_proto = out.File
	file_common_proto_inventory_inventory_proto_goTypes = nil
	file_common_proto_inventory_inventory_proto_depIdxs = nil
}
