// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: common/proto/order/order.proto

package orderProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Main Models
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_common_proto_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_common_proto_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	TotalPrice    float32                `protobuf:"fixed32,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	PaymentLinkId string                 `protobuf:"bytes,6,opt,name=payment_link_id,json=paymentLinkId,proto3" json:"payment_link_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,7,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_common_proto_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_common_proto_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetPaymentLinkId() string {
	if x != nil {
		return x.PaymentLinkId
	}
	return ""
}

func (x *Order) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Order Create Models
type OrderCreatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OrderItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreatePayload) Reset() {
	*x = OrderCreatePayload{}
	mi := &file_common_proto_order_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatePayload) ProtoMessage() {}

func (x *OrderCreatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_order_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatePayload.ProtoReflect.Descriptor instead.
func (*OrderCreatePayload) Descriptor() ([]byte, []int) {
	return file_common_proto_order_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCreatePayload) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderCreatePayload) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// Get Order By ID & Customer ID
type GetOrderByIDAndCustomerIDPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDAndCustomerIDPayload) Reset() {
	*x = GetOrderByIDAndCustomerIDPayload{}
	mi := &file_common_proto_order_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDAndCustomerIDPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDAndCustomerIDPayload) ProtoMessage() {}

func (x *GetOrderByIDAndCustomerIDPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_order_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDAndCustomerIDPayload.ProtoReflect.Descriptor instead.
func (*GetOrderByIDAndCustomerIDPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_order_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderByIDAndCustomerIDPayload) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderByIDAndCustomerIDPayload) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// Set Order Payment Link ID
type SetOrderPaymentLinkIDPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PaymentLinkId string                 `protobuf:"bytes,3,opt,name=payment_link_id,json=paymentLinkId,proto3" json:"payment_link_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOrderPaymentLinkIDPayload) Reset() {
	*x = SetOrderPaymentLinkIDPayload{}
	mi := &file_common_proto_order_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOrderPaymentLinkIDPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrderPaymentLinkIDPayload) ProtoMessage() {}

func (x *SetOrderPaymentLinkIDPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_order_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrderPaymentLinkIDPayload.ProtoReflect.Descriptor instead.
func (*SetOrderPaymentLinkIDPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_order_order_proto_rawDescGZIP(), []int{4}
}

func (x *SetOrderPaymentLinkIDPayload) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SetOrderPaymentLinkIDPayload) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SetOrderPaymentLinkIDPayload) GetPaymentLinkId() string {
	if x != nil {
		return x.PaymentLinkId
	}
	return ""
}

// Cancel Order
type CancelOrderPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderPayload) Reset() {
	*x = CancelOrderPayload{}
	mi := &file_common_proto_order_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderPayload) ProtoMessage() {}

func (x *CancelOrderPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_order_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderPayload.ProtoReflect.Descriptor instead.
func (*CancelOrderPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_order_order_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOrderPayload) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderPayload) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// Set Order Paid
type SetOrderPaidPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOrderPaidPayload) Reset() {
	*x = SetOrderPaidPayload{}
	mi := &file_common_proto_order_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOrderPaidPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrderPaidPayload) ProtoMessage() {}

func (x *SetOrderPaidPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_order_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrderPaidPayload.ProtoReflect.Descriptor instead.
func (*SetOrderPaidPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_order_order_proto_rawDescGZIP(), []int{6}
}

func (x *SetOrderPaidPayload) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SetOrderPaidPayload) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SetOrderPaidPayload) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

var File_common_proto_order_order_proto protoreflect.FileDescriptor

const file_common_proto_order_order_proto_rawDesc = "" +
	"\n" +
	"\x1ecommon/proto/order/order.proto\x12\n" +
	"orderProto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"e\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"\xe6\x02\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.orderProto.OrderItemR\x05items\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\x02R\n" +
	"totalPrice\x12&\n" +
	"\x0fpayment_link_id\x18\x06 \x01(\tR\rpaymentLinkId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\a \x01(\tR\tpaymentId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"b\n" +
	"\x12OrderCreatePayload\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.orderProto.OrderItemR\x05items\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\"^\n" +
	" GetOrderByIDAndCustomerIDPayload\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\"\x82\x01\n" +
	"\x1cSetOrderPaymentLinkIDPayload\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12&\n" +
	"\x0fpayment_link_id\x18\x03 \x01(\tR\rpaymentLinkId\"P\n" +
	"\x12CancelOrderPayload\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\"p\n" +
	"\x13SetOrderPaidPayload\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x03 \x01(\tR\tpaymentId2\x99\x03\n" +
	"\fOrderService\x12@\n" +
	"\vCreateOrder\x12\x1e.orderProto.OrderCreatePayload\x1a\x11.orderProto.Order\x12\\\n" +
	"\x19GetOrderByIDAndCustomerID\x12,.orderProto.GetOrderByIDAndCustomerIDPayload\x1a\x11.orderProto.Order\x12Y\n" +
	"\x15SetOrderPaymentLinkID\x12(.orderProto.SetOrderPaymentLinkIDPayload\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\vCancelOrder\x12\x1e.orderProto.CancelOrderPayload\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\fSetOrderPaid\x12\x1f.orderProto.SetOrderPaidPayload\x1a\x16.google.protobuf.EmptyB\x18Z\x16order/proto;orderProtob\x06proto3"

var (
	file_common_proto_order_order_proto_rawDescOnce sync.Once
	file_common_proto_order_order_proto_rawDescData []byte
)

func file_common_proto_order_order_proto_rawDescGZIP() []byte {
	file_common_proto_order_order_proto_rawDescOnce.Do(func() {
		file_common_proto_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_order_order_proto_rawDesc), len(file_common_proto_order_order_proto_rawDesc)))
	})
	return file_common_proto_order_order_proto_rawDescData
}

var file_common_proto_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_proto_order_order_proto_goTypes = []any{
	(*OrderItem)(nil),                        // 0: orderProto.OrderItem
	(*Order)(nil),                            // 1: orderProto.Order
	(*OrderCreatePayload)(nil),               // 2: orderProto.OrderCreatePayload
	(*GetOrderByIDAndCustomerIDPayload)(nil), // 3: orderProto.GetOrderByIDAndCustomerIDPayload
	(*SetOrderPaymentLinkIDPayload)(nil),     // 4: orderProto.SetOrderPaymentLinkIDPayload
	(*CancelOrderPayload)(nil),               // 5: orderProto.CancelOrderPayload
	(*SetOrderPaidPayload)(nil),              // 6: orderProto.SetOrderPaidPayload
	(*timestamppb.Timestamp)(nil),            // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 8: google.protobuf.Empty
}
var file_common_proto_order_order_proto_depIdxs = []int32{
	0, // 0: orderProto.Order.items:type_name -> orderProto.OrderItem
	7, // 1: orderProto.Order.created_at:type_name -> google.protobuf.Timestamp
	7, // 2: orderProto.Order.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: orderProto.OrderCreatePayload.items:type_name -> orderProto.OrderItem
	2, // 4: orderProto.OrderService.CreateOrder:input_type -> orderProto.OrderCreatePayload
	3, // 5: orderProto.OrderService.GetOrderByIDAndCustomerID:input_type -> orderProto.GetOrderByIDAndCustomerIDPayload
	4, // 6: orderProto.OrderService.SetOrderPaymentLinkID:input_type -> orderProto.SetOrderPaymentLinkIDPayload
	5, // 7: orderProto.OrderService.CancelOrder:input_type -> orderProto.CancelOrderPayload
	6, // 8: orderProto.OrderService.SetOrderPaid:input_type -> orderProto.SetOrderPaidPayload
	1, // 9: orderProto.OrderService.CreateOrder:output_type -> orderProto.Order
	1, // 10: orderProto.OrderService.GetOrderByIDAndCustomerID:output_type -> orderProto.Order
	8, // 11: orderProto.OrderService.SetOrderPaymentLinkID:output_type -> google.protobuf.Empty
	8, // 12: orderProto.OrderService.CancelOrder:output_type -> google.protobuf.Empty
	8, // 13: orderProto.OrderService.SetOrderPaid:output_type -> google.protobuf.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_proto_order_order_proto_init() }
func file_common_proto_order_order_proto_init() {
	if File_common_proto_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_order_order_proto_rawDesc), len(file_common_proto_order_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_order_order_proto_goTypes,
		DependencyIndexes: file_common_proto_order_order_proto_depIdxs,
		MessageInfos:      file_common_proto_order_order_proto_msgTypes,
	}.Build()
	File_common_proto_order_order_proto = out.File
	file_common_proto_order_order_proto_goTypes = nil
	file_common_proto_order_order_proto_depIdxs = nil
}
