// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: common/proto/product/product.proto

package productProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Main Models
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	PriceId       string                 `protobuf:"bytes,7,opt,name=price_id,json=priceId,proto3" json:"price_id,omitempty"`
	NetWeight     float32                `protobuf:"fixed32,8,opt,name=net_weight,json=netWeight,proto3" json:"net_weight,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_common_proto_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_common_proto_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetPriceId() string {
	if x != nil {
		return x.PriceId
	}
	return ""
}

func (x *Product) GetNetWeight() float32 {
	if x != nil {
		return x.NetWeight
	}
	return 0
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Product Create Models
type ProductCreatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	NetWeight     float32                `protobuf:"fixed32,6,opt,name=net_weight,json=netWeight,proto3" json:"net_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCreatePayload) Reset() {
	*x = ProductCreatePayload{}
	mi := &file_common_proto_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCreatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCreatePayload) ProtoMessage() {}

func (x *ProductCreatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCreatePayload.ProtoReflect.Descriptor instead.
func (*ProductCreatePayload) Descriptor() ([]byte, []int) {
	return file_common_proto_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductCreatePayload) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ProductCreatePayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCreatePayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductCreatePayload) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductCreatePayload) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductCreatePayload) GetNetWeight() float32 {
	if x != nil {
		return x.NetWeight
	}
	return 0
}

// Get Product By ID & Company ID
type GetProductByIDAndCompanyIDPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIDAndCompanyIDPayload) Reset() {
	*x = GetProductByIDAndCompanyIDPayload{}
	mi := &file_common_proto_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIDAndCompanyIDPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIDAndCompanyIDPayload) ProtoMessage() {}

func (x *GetProductByIDAndCompanyIDPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIDAndCompanyIDPayload.ProtoReflect.Descriptor instead.
func (*GetProductByIDAndCompanyIDPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductByIDAndCompanyIDPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetProductByIDAndCompanyIDPayload) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type GetProductByIDPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIDPayload) Reset() {
	*x = GetProductByIDPayload{}
	mi := &file_common_proto_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIDPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIDPayload) ProtoMessage() {}

func (x *GetProductByIDPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIDPayload.ProtoReflect.Descriptor instead.
func (*GetProductByIDPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductByIDPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Product Update Models
type ProductUpdatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	NetWeight     float32                `protobuf:"fixed32,7,opt,name=net_weight,json=netWeight,proto3" json:"net_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductUpdatePayload) Reset() {
	*x = ProductUpdatePayload{}
	mi := &file_common_proto_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUpdatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUpdatePayload) ProtoMessage() {}

func (x *ProductUpdatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUpdatePayload.ProtoReflect.Descriptor instead.
func (*ProductUpdatePayload) Descriptor() ([]byte, []int) {
	return file_common_proto_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *ProductUpdatePayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductUpdatePayload) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ProductUpdatePayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductUpdatePayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductUpdatePayload) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductUpdatePayload) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductUpdatePayload) GetNetWeight() float32 {
	if x != nil {
		return x.NetWeight
	}
	return 0
}

// List Products By CompanyID Models
type ListProductsByCompanyIDPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsByCompanyIDPayload) Reset() {
	*x = ListProductsByCompanyIDPayload{}
	mi := &file_common_proto_product_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsByCompanyIDPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsByCompanyIDPayload) ProtoMessage() {}

func (x *ListProductsByCompanyIDPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_product_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsByCompanyIDPayload.ProtoReflect.Descriptor instead.
func (*ListProductsByCompanyIDPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_product_product_proto_rawDescGZIP(), []int{5}
}

func (x *ListProductsByCompanyIDPayload) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListProductsByCompanyIDPayload) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProductsByCompanyIDPayload) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_common_proto_product_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_product_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_product_product_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Delete Product Models
type DeleteProductPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductPayload) Reset() {
	*x = DeleteProductPayload{}
	mi := &file_common_proto_product_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductPayload) ProtoMessage() {}

func (x *DeleteProductPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_product_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductPayload.ProtoReflect.Descriptor instead.
func (*DeleteProductPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_product_product_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProductPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteProductPayload) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

// Set Product Price ID Model
type SetProductPriceIDPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	PriceId       string                 `protobuf:"bytes,3,opt,name=price_id,json=priceId,proto3" json:"price_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProductPriceIDPayload) Reset() {
	*x = SetProductPriceIDPayload{}
	mi := &file_common_proto_product_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProductPriceIDPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProductPriceIDPayload) ProtoMessage() {}

func (x *SetProductPriceIDPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_product_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProductPriceIDPayload.ProtoReflect.Descriptor instead.
func (*SetProductPriceIDPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_product_product_proto_rawDescGZIP(), []int{8}
}

func (x *SetProductPriceIDPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetProductPriceIDPayload) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *SetProductPriceIDPayload) GetPriceId() string {
	if x != nil {
		return x.PriceId
	}
	return ""
}

var File_common_proto_product_product_proto protoreflect.FileDescriptor

const file_common_proto_product_product_proto_rawDesc = "" +
	"\n" +
	"\"common/proto/product/product.proto\x12\fproductProto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd0\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x02R\x05price\x12\x19\n" +
	"\bprice_id\x18\a \x01(\tR\apriceId\x12\x1d\n" +
	"\n" +
	"net_weight\x18\b \x01(\x02R\tnetWeight\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbc\x01\n" +
	"\x14ProductCreatePayload\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12\x1d\n" +
	"\n" +
	"net_weight\x18\x06 \x01(\x02R\tnetWeight\"R\n" +
	"!GetProductByIDAndCompanyIDPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\"'\n" +
	"\x15GetProductByIDPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xcc\x01\n" +
	"\x14ProductUpdatePayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x02R\x05price\x12\x1d\n" +
	"\n" +
	"net_weight\x18\a \x01(\x02R\tnetWeight\"m\n" +
	"\x1eListProductsByCompanyIDPayload\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"j\n" +
	"\x14ListProductsResponse\x121\n" +
	"\bproducts\x18\x01 \x03(\v2\x15.productProto.ProductR\bproducts\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"E\n" +
	"\x14DeleteProductPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\"d\n" +
	"\x18SetProductPriceIDPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x19\n" +
	"\bprice_id\x18\x03 \x01(\tR\apriceId2\xeb\x04\n" +
	"\x0eProductService\x12J\n" +
	"\rCreateProduct\x12\".productProto.ProductCreatePayload\x1a\x15.productProto.Product\x12d\n" +
	"\x1aGetProductByIDAndCompanyID\x12/.productProto.GetProductByIDAndCompanyIDPayload\x1a\x15.productProto.Product\x12L\n" +
	"\x0eGetProductByID\x12#.productProto.GetProductByIDPayload\x1a\x15.productProto.Product\x12J\n" +
	"\rUpdateProduct\x12\".productProto.ProductUpdatePayload\x1a\x15.productProto.Product\x12k\n" +
	"\x17ListProductsByCompanyID\x12,.productProto.ListProductsByCompanyIDPayload\x1a\".productProto.ListProductsResponse\x12K\n" +
	"\rDeleteProduct\x12\".productProto.DeleteProductPayload\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\x11SetProductPriceID\x12&.productProto.SetProductPriceIDPayload\x1a\x16.google.protobuf.EmptyB\x1cZ\x1aproduct/proto;productProtob\x06proto3"

var (
	file_common_proto_product_product_proto_rawDescOnce sync.Once
	file_common_proto_product_product_proto_rawDescData []byte
)

func file_common_proto_product_product_proto_rawDescGZIP() []byte {
	file_common_proto_product_product_proto_rawDescOnce.Do(func() {
		file_common_proto_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_product_product_proto_rawDesc), len(file_common_proto_product_product_proto_rawDesc)))
	})
	return file_common_proto_product_product_proto_rawDescData
}

var file_common_proto_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_common_proto_product_product_proto_goTypes = []any{
	(*Product)(nil),                           // 0: productProto.Product
	(*ProductCreatePayload)(nil),              // 1: productProto.ProductCreatePayload
	(*GetProductByIDAndCompanyIDPayload)(nil), // 2: productProto.GetProductByIDAndCompanyIDPayload
	(*GetProductByIDPayload)(nil),             // 3: productProto.GetProductByIDPayload
	(*ProductUpdatePayload)(nil),              // 4: productProto.ProductUpdatePayload
	(*ListProductsByCompanyIDPayload)(nil),    // 5: productProto.ListProductsByCompanyIDPayload
	(*ListProductsResponse)(nil),              // 6: productProto.ListProductsResponse
	(*DeleteProductPayload)(nil),              // 7: productProto.DeleteProductPayload
	(*SetProductPriceIDPayload)(nil),          // 8: productProto.SetProductPriceIDPayload
	(*timestamppb.Timestamp)(nil),             // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                     // 10: google.protobuf.Empty
}
var file_common_proto_product_product_proto_depIdxs = []int32{
	9,  // 0: productProto.Product.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: productProto.Product.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: productProto.ListProductsResponse.products:type_name -> productProto.Product
	1,  // 3: productProto.ProductService.CreateProduct:input_type -> productProto.ProductCreatePayload
	2,  // 4: productProto.ProductService.GetProductByIDAndCompanyID:input_type -> productProto.GetProductByIDAndCompanyIDPayload
	3,  // 5: productProto.ProductService.GetProductByID:input_type -> productProto.GetProductByIDPayload
	4,  // 6: productProto.ProductService.UpdateProduct:input_type -> productProto.ProductUpdatePayload
	5,  // 7: productProto.ProductService.ListProductsByCompanyID:input_type -> productProto.ListProductsByCompanyIDPayload
	7,  // 8: productProto.ProductService.DeleteProduct:input_type -> productProto.DeleteProductPayload
	8,  // 9: productProto.ProductService.SetProductPriceID:input_type -> productProto.SetProductPriceIDPayload
	0,  // 10: productProto.ProductService.CreateProduct:output_type -> productProto.Product
	0,  // 11: productProto.ProductService.GetProductByIDAndCompanyID:output_type -> productProto.Product
	0,  // 12: productProto.ProductService.GetProductByID:output_type -> productProto.Product
	0,  // 13: productProto.ProductService.UpdateProduct:output_type -> productProto.Product
	6,  // 14: productProto.ProductService.ListProductsByCompanyID:output_type -> productProto.ListProductsResponse
	10, // 15: productProto.ProductService.DeleteProduct:output_type -> google.protobuf.Empty
	10, // 16: productProto.ProductService.SetProductPriceID:output_type -> google.protobuf.Empty
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_common_proto_product_product_proto_init() }
func file_common_proto_product_product_proto_init() {
	if File_common_proto_product_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_product_product_proto_rawDesc), len(file_common_proto_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_product_product_proto_goTypes,
		DependencyIndexes: file_common_proto_product_product_proto_depIdxs,
		MessageInfos:      file_common_proto_product_product_proto_msgTypes,
	}.Build()
	File_common_proto_product_product_proto = out.File
	file_common_proto_product_product_proto_goTypes = nil
	file_common_proto_product_product_proto_depIdxs = nil
}
